import { CampaignTableDataType } from '../../features/MyCampaigns/MyCampaignsTable/MyCampaignsTableDataTypes';

export const DATA_SOURCE: CampaignTableDataType[] = [
  {
    key: '1',
    campaignName: 'UD_FR - DBM - Amnet - CIVP',
    start: '19/05/2022',
    end: '31/05/2036',
    bookedImpressions: -1,
    deliveredImpressions: 1,
    clicks: 22,
    ctr: 100,
    cpm: 1000,
    budget: -1,
    spend: null,
    daysLeft: 4948,
    margin: 0,
    osi: null,
    platform: 'hello',
    children: [
      {
        key: '11',
        campaignName: 'UD_FR - DBM - Amnet - CIVP',
        start: '19/05/2022',
        end: '31/05/2036',
        bookedImpressions: -1,
        deliveredImpressions: 1,
        clicks: 22,
        ctr: 100,
        cpm: 1000,
        budget: -1,
        spend: null,
        daysLeft: 4948,
        margin: 0,
        osi: null,
        platform: 'hello',
        children: null,
      },
      {
        key: '12',
        campaignName: 'UD_Azerion FI_Dentsu Paulig_DV360',
        start: '23/05/2022',
        end: '23/05/2036',
        bookedImpressions: -1,
        deliveredImpressions: 1,
        clicks: 22,
        ctr: 100,
        cpm: 1000,
        budget: -1,
        spend: null,
        daysLeft: 4948,
        margin: 0,
        osi: null,
        platform: 'hello',
        children: null,
      },
      {
        key: '13',
        campaignName: 'UD_FR - DBM - Amnet - CIVP',
        start: '19/05/2022',
        end: '31/05/2036',
        bookedImpressions: -1,
        deliveredImpressions: 1,
        clicks: 22,
        ctr: 100,
        cpm: 1000,
        budget: -1,
        spend: null,
        daysLeft: 4948,
        margin: 0,
        osi: null,
        platform: 'hello',
        children: null,
      },
      {
        key: '14',
        campaignName: 'UD_Azerion FI_Dentsu Paulig_DV360',
        start: '23/05/2022',
        end: '23/05/2036',
        bookedImpressions: -1,
        deliveredImpressions: 1,
        clicks: 22,
        ctr: 100,
        cpm: 1000,
        budget: -1,
        spend: null,
        daysLeft: 4948,
        margin: 0,
        osi: null,
        platform: 'hello',
        children: null,
      },
    ],
  },
  {
    key: '2',
    campaignName: 'UD_Azerion FI_Dentsu Paulig_DV360',
    start: '23/05/2022',
    end: '23/05/2036',
    bookedImpressions: -1,
    deliveredImpressions: 1,
    clicks: 22,
    ctr: 100,
    cpm: 1000,
    budget: -1,
    spend: null,
    daysLeft: 4948,
    margin: 0,
    osi: null,
    platform: 'hello',
    children: null,
  },
];

export const PLATFORM_OPTIONS = [
  { value: 'marketplace', label: 'Marketplace' },
  { value: 'xandr', label: 'Xandr' },
  { value: 'dv360', label: 'Dv360' },
];

export const BUSINESS_UNIT_OPTIONS = [
  { value: 'azInternal', label: 'Azerion Internal' },
  { value: 'azBD', label: 'Azerion Bangladesh' },
  { value: 'azUK', label: 'Azerion UK' },
  { value: 'azDuch', label: 'Azerion DUCH' },
];

export const STATUS_OPTIONS = [
  { value: 'draft', label: 'Draft' },
  { value: 'active', label: 'Active' },
  { value: 'pause', label: 'Pause' },
  { value: 'finished', label: 'Finished' },
];